package com.example.entity;
// Generated Feb 7, 2018 12:36:06 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "booking", catalog = "restaurantconceptual")
public class Booking implements java.io.Serializable {

	private Integer bookingId;
	private Customer customer;
	private Tables tables;
	private String dateOfBooking;
	private int numberInParty;

	public Booking() {
	}

	public Booking(Customer customer, Tables tables, String dateOfBooking, int numberInParty) {
		this.customer = customer;
		this.tables = tables;
		this.dateOfBooking = dateOfBooking;
		this.numberInParty = numberInParty;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "booking_id", unique = true, nullable = false)
	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "table_number", nullable = false)
	public Tables getTables() {
		return this.tables;
	}

	public void setTables(Tables tables) {
		this.tables = tables;
	}

	@Column(name = "date_of_booking", nullable = false, length = 100)
	public String getDateOfBooking() {
		return this.dateOfBooking;
	}

	public void setDateOfBooking(String dateOfBooking) {
		this.dateOfBooking = dateOfBooking;
	}

	@Column(name = "number_in_party", nullable = false)
	public int getNumberInParty() {
		return this.numberInParty;
	}

	public void setNumberInParty(int numberInParty) {
		this.numberInParty = numberInParty;
	}

}
