package com.example.entity;
// Generated Feb 7, 2018 12:36:06 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "restaurantconceptual")
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private String customerFirstName;
	private String customerSurname;
	private String phoneNumber;
	private String cellNumber;
	private String emailAddress;
	private String otherCustomerDetails;
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public Customer() {
	}

	public Customer(String customerFirstName, String customerSurname, String phoneNumber, String cellNumber,
			String emailAddress, String otherCustomerDetails) {
		this.customerFirstName = customerFirstName;
		this.customerSurname = customerSurname;
		this.phoneNumber = phoneNumber;
		this.cellNumber = cellNumber;
		this.emailAddress = emailAddress;
		this.otherCustomerDetails = otherCustomerDetails;
	}

	public Customer(String customerFirstName, String customerSurname, String phoneNumber, String cellNumber,
			String emailAddress, String otherCustomerDetails, Set<Booking> bookings) {
		this.customerFirstName = customerFirstName;
		this.customerSurname = customerSurname;
		this.phoneNumber = phoneNumber;
		this.cellNumber = cellNumber;
		this.emailAddress = emailAddress;
		this.otherCustomerDetails = otherCustomerDetails;
		this.bookings = bookings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customer_id", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "customer_first_name", nullable = false, length = 100)
	public String getCustomerFirstName() {
		return this.customerFirstName;
	}

	public void setCustomerFirstName(String customerFirstName) {
		this.customerFirstName = customerFirstName;
	}

	@Column(name = "customer_surname", nullable = false, length = 100)
	public String getCustomerSurname() {
		return this.customerSurname;
	}

	public void setCustomerSurname(String customerSurname) {
		this.customerSurname = customerSurname;
	}

	@Column(name = "phone_number", nullable = false, length = 100)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "cell_number", nullable = false, length = 100)
	public String getCellNumber() {
		return this.cellNumber;
	}

	public void setCellNumber(String cellNumber) {
		this.cellNumber = cellNumber;
	}

	@Column(name = "email_address", nullable = false, length = 100)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "other_customer_details", nullable = false, length = 100)
	public String getOtherCustomerDetails() {
		return this.otherCustomerDetails;
	}

	public void setOtherCustomerDetails(String otherCustomerDetails) {
		this.otherCustomerDetails = otherCustomerDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
