package com.example.entity;
// Generated Feb 7, 2018 12:36:06 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IngredientType generated by hbm2java
 */
@Entity
@Table(name = "ingredient_type", catalog = "restaurantconceptual")
public class IngredientType implements java.io.Serializable {

	private Integer ingredientTypeCode;
	private String ingredientTypeDecscription;
	private Set<Ingredients> ingredientses = new HashSet<Ingredients>(0);

	public IngredientType() {
	}

	public IngredientType(String ingredientTypeDecscription) {
		this.ingredientTypeDecscription = ingredientTypeDecscription;
	}

	public IngredientType(String ingredientTypeDecscription, Set<Ingredients> ingredientses) {
		this.ingredientTypeDecscription = ingredientTypeDecscription;
		this.ingredientses = ingredientses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ingredient_type_code", unique = true, nullable = false)
	public Integer getIngredientTypeCode() {
		return this.ingredientTypeCode;
	}

	public void setIngredientTypeCode(Integer ingredientTypeCode) {
		this.ingredientTypeCode = ingredientTypeCode;
	}

	@Column(name = "ingredient_type_decscription", nullable = false, length = 100)
	public String getIngredientTypeDecscription() {
		return this.ingredientTypeDecscription;
	}

	public void setIngredientTypeDecscription(String ingredientTypeDecscription) {
		this.ingredientTypeDecscription = ingredientTypeDecscription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ingredientType")
	public Set<Ingredients> getIngredientses() {
		return this.ingredientses;
	}

	public void setIngredientses(Set<Ingredients> ingredientses) {
		this.ingredientses = ingredientses;
	}

}
