package com.example.entity;
// Generated Feb 7, 2018 12:36:06 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ingredients generated by hbm2java
 */
@Entity
@Table(name = "ingredients", catalog = "restaurantconceptual")
public class Ingredients implements java.io.Serializable {

	private Integer ingredientId;
	private IngredientType ingredientType;
	private String ingredientName;
	private Set<MenuItemIngredient> menuItemIngredients = new HashSet<MenuItemIngredient>(0);

	public Ingredients() {
	}

	public Ingredients(IngredientType ingredientType, String ingredientName) {
		this.ingredientType = ingredientType;
		this.ingredientName = ingredientName;
	}

	public Ingredients(IngredientType ingredientType, String ingredientName,
			Set<MenuItemIngredient> menuItemIngredients) {
		this.ingredientType = ingredientType;
		this.ingredientName = ingredientName;
		this.menuItemIngredients = menuItemIngredients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ingredient_id", unique = true, nullable = false)
	public Integer getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(Integer ingredientId) {
		this.ingredientId = ingredientId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ingredient_type_code", nullable = false)
	public IngredientType getIngredientType() {
		return this.ingredientType;
	}

	public void setIngredientType(IngredientType ingredientType) {
		this.ingredientType = ingredientType;
	}

	@Column(name = "ingredient_name", nullable = false, length = 100)
	public String getIngredientName() {
		return this.ingredientName;
	}

	public void setIngredientName(String ingredientName) {
		this.ingredientName = ingredientName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ingredients")
	public Set<MenuItemIngredient> getMenuItemIngredients() {
		return this.menuItemIngredients;
	}

	public void setMenuItemIngredients(Set<MenuItemIngredient> menuItemIngredients) {
		this.menuItemIngredients = menuItemIngredients;
	}

}
