package com.example.entity;
// Generated Feb 7, 2018 12:36:06 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MenuItemIngredient generated by hbm2java
 */
@Entity
@Table(name = "menu_item_ingredient", catalog = "restaurantconceptual")
public class MenuItemIngredient implements java.io.Serializable {

	private Integer menuItemIngredientId;
	private Ingredients ingredients;
	private MenuItem menuItem;
	private int itemQuantity;

	public MenuItemIngredient() {
	}

	public MenuItemIngredient(Ingredients ingredients, MenuItem menuItem, int itemQuantity) {
		this.ingredients = ingredients;
		this.menuItem = menuItem;
		this.itemQuantity = itemQuantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "menu_item_ingredient_id", unique = true, nullable = false)
	public Integer getMenuItemIngredientId() {
		return this.menuItemIngredientId;
	}

	public void setMenuItemIngredientId(Integer menuItemIngredientId) {
		this.menuItemIngredientId = menuItemIngredientId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ingredient_id", nullable = false)
	public Ingredients getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(Ingredients ingredients) {
		this.ingredients = ingredients;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "menu_item_id", nullable = false)
	public MenuItem getMenuItem() {
		return this.menuItem;
	}

	public void setMenuItem(MenuItem menuItem) {
		this.menuItem = menuItem;
	}

	@Column(name = "item_quantity", nullable = false)
	public int getItemQuantity() {
		return this.itemQuantity;
	}

	public void setItemQuantity(int itemQuantity) {
		this.itemQuantity = itemQuantity;
	}

}
