package com.example.entity;
// Generated Feb 7, 2018 12:36:06 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderMenuItem generated by hbm2java
 */
@Entity
@Table(name = "order_menu_item", catalog = "restaurantconceptual")
public class OrderMenuItem implements java.io.Serializable {

	private Integer orderMenuItemId;
	private MenuItem menuItem;
	private Orders orders;
	private int orderMenuItemQuantity;
	private String orderMenuItemComments;

	public OrderMenuItem() {
	}

	public OrderMenuItem(MenuItem menuItem, Orders orders, int orderMenuItemQuantity, String orderMenuItemComments) {
		this.menuItem = menuItem;
		this.orders = orders;
		this.orderMenuItemQuantity = orderMenuItemQuantity;
		this.orderMenuItemComments = orderMenuItemComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_menu_item_id", unique = true, nullable = false)
	public Integer getOrderMenuItemId() {
		return this.orderMenuItemId;
	}

	public void setOrderMenuItemId(Integer orderMenuItemId) {
		this.orderMenuItemId = orderMenuItemId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "menu_item_id", nullable = false)
	public MenuItem getMenuItem() {
		return this.menuItem;
	}

	public void setMenuItem(MenuItem menuItem) {
		this.menuItem = menuItem;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "order_id", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "order_menu_item_quantity", nullable = false)
	public int getOrderMenuItemQuantity() {
		return this.orderMenuItemQuantity;
	}

	public void setOrderMenuItemQuantity(int orderMenuItemQuantity) {
		this.orderMenuItemQuantity = orderMenuItemQuantity;
	}

	@Column(name = "order_menu_item_comments", nullable = false, length = 100)
	public String getOrderMenuItemComments() {
		return this.orderMenuItemComments;
	}

	public void setOrderMenuItemComments(String orderMenuItemComments) {
		this.orderMenuItemComments = orderMenuItemComments;
	}

}
