package com.example.entity;
// Generated Feb 7, 2018 12:36:06 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StaffRole generated by hbm2java
 */
@Entity
@Table(name = "staff_role", catalog = "restaurantconceptual")
public class StaffRole implements java.io.Serializable {

	private Integer staffRoleCode;
	private String staffRoleDecscription;
	private Set<Staff> staffs = new HashSet<Staff>(0);

	public StaffRole() {
	}

	public StaffRole(String staffRoleDecscription) {
		this.staffRoleDecscription = staffRoleDecscription;
	}

	public StaffRole(String staffRoleDecscription, Set<Staff> staffs) {
		this.staffRoleDecscription = staffRoleDecscription;
		this.staffs = staffs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "staff_role_code", unique = true, nullable = false)
	public Integer getStaffRoleCode() {
		return this.staffRoleCode;
	}

	public void setStaffRoleCode(Integer staffRoleCode) {
		this.staffRoleCode = staffRoleCode;
	}

	@Column(name = "staff_role_decscription", nullable = false, length = 100)
	public String getStaffRoleDecscription() {
		return this.staffRoleDecscription;
	}

	public void setStaffRoleDecscription(String staffRoleDecscription) {
		this.staffRoleDecscription = staffRoleDecscription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staffRole")
	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}

	@Override
	public String toString() {
		return "StaffRole [staffRoleCode=" + staffRoleCode + ", staffRoleDecscription=" + staffRoleDecscription + "]";
	}

}
