package com.example.entity;
// Generated Feb 7, 2018 12:36:06 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "staff", catalog = "restaurantconceptual")
public class Staff implements java.io.Serializable {

	private Integer staffId;
	private StaffRole staffRole;
	private String staffFirstName;
	private String staffLastName;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Staff() {
	}

	public Staff(StaffRole staffRole, String staffFirstName, String staffLastName) {
		this.staffRole = staffRole;
		this.staffFirstName = staffFirstName;
		this.staffLastName = staffLastName;
	}

	public Staff(StaffRole staffRole, String staffFirstName, String staffLastName, Set<Orders> orderses) {
		this.staffRole = staffRole;
		this.staffFirstName = staffFirstName;
		this.staffLastName = staffLastName;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "staff_id", unique = true, nullable = false)
	public Integer getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "staff_role_code", nullable = false)
	public StaffRole getStaffRole() {
		return this.staffRole;
	}

	public void setStaffRole(StaffRole staffRole) {
		this.staffRole = staffRole;
	}

	@Column(name = "staff_first_name", nullable = false, length = 100)
	public String getStaffFirstName() {
		return this.staffFirstName;
	}

	public void setStaffFirstName(String staffFirstName) {
		this.staffFirstName = staffFirstName;
	}

	@Column(name = "staff_last_name", nullable = false, length = 100)
	public String getStaffLastName() {
		return this.staffLastName;
	}

	public void setStaffLastName(String staffLastName) {
		this.staffLastName = staffLastName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
