package com.example.entity;
// Generated Feb 7, 2018 12:36:06 AM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tables generated by hbm2java
 */
@Entity
@Table(name = "tables", catalog = "restaurantconceptual")
public class Tables implements java.io.Serializable {

	private Integer tableNumber;
	private String tableDetails;
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public Tables() {
	}

	public Tables(String tableDetails) {
		this.tableDetails = tableDetails;
	}

	public Tables(String tableDetails, Set<Orders> orderses, Set<Booking> bookings) {
		this.tableDetails = tableDetails;
		this.orderses = orderses;
		this.bookings = bookings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "table_number", unique = true, nullable = false)
	public Integer getTableNumber() {
		return this.tableNumber;
	}

	public void setTableNumber(Integer tableNumber) {
		this.tableNumber = tableNumber;
	}

	@Column(name = "table_details", nullable = false, length = 100)
	public String getTableDetails() {
		return this.tableDetails;
	}

	public void setTableDetails(String tableDetails) {
		this.tableDetails = tableDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tables")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tables")
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
